version: "3.4"

networks:
 app_network:
   name: mcat-hms-network
   driver: bridge

services:
  api:
    container_name: mcat-hms-api
    image: mcat-hms-api  
    build:
      target: build
      # target: prod
      context: ./
    volumes:
      - ./:/app
    ports:
      - 5900:5900
    env_file:
      - ./.env
    networks:
      - app_network

  newman:
    image: postman/newman:alpine
    container_name: mcat-hms-newman
    entrypoint: [""]
    command: >
      sh -c "sleep 30s &&
             newman run /app/testing/postman_collection.json --env-var "url=api:5900""
    volumes:
      - ./testing:/app/testing
    depends_on:
      - "api"
    networks:
      - app_network        