version: "3.4"

services:
  mcat-hms:
    build:
      context: ./
    volumes:
      - ./:/app
    ports:
      - 5900:5900
    env_file:
      - ./.env
    entrypoint: CompileDaemon --build="go build main.go" --command=./main
